name: Update momo

# Controls when the action will run.
on:
  schedule:
    - cron: '20 22 * * 5'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master

      # Set-timezone
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 'Working'
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` > time.log
          
      - name: Commit #上传新的time.log到仓库
        run: |
          git config --global user.email iicovo@163.com
          git config --global user.name Gonfeii
          git add time.log
          git commit -m "Auto Update" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
